services:
  mongodb:
    image: mongo:7.0
    container_name: email-builder-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: emailbuilder
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - email-builder-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: email-builder-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/emailbuilder?authSource=admin
      - DATABASE_NAME=emailbuilder
    depends_on:
      - mongodb
    networks:
      - email-builder-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email-builder-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - email-builder-network

  # Background tasks handled by built-in BackgroundTaskManager
  # No external dependencies needed

volumes:
  mongodb_data:
    driver: local

networks:
  email-builder-network:
    driver: bridge 